### ISSUE TITLE
End time of run summary is one sample too early

### ISSUE THREAD

**Issue by kkappler** [kujaku11/mth5#102]
When accessing a run_ts from a run obj using the slicing tools:

> run_ts = run_obj.to_runts(start=start, end=end)

When I use the end time from the channel_summary, I wind up with one fewer samples than expected, i.e. the last sample is dropped when end equals the end time of the run.  

I looked into this, thinking that this was round off error in the slicer, but when I went into master_station_run_channel around lines 1533, 1534, I compared the end time I was passing to the end time of the channel in the mth5
            

>     ts_obj = ch_obj.time_slice(start, end=end, n_samples=n_samples)
I compared the end time I was passing to the end time of the channel in the mth5, and found that the end time I was passing from the channel_summary, was 1 second earlier than expected.  i.e. 

```ch_obj.end
Out[2]: 1980-01-01T11:06:40+00:00```

But the end I had passed (which I got from channel_summary) was
```datetime.datetime(1980, 1, 1, 11, 6, 39)```

**Comment by kkappler** [comment]
These kind of issues associated with open, half-open, and closed intervals can get tricky.  We may want to update channel summary so that the timestamp is 1 sample later, but also add a line of logic in the slicer that if the end given is exactly equal to the end of the run, we replace it with None, to avoid a possible index error.

**Comment by kujaku11** [comment]
Should be fixed now.
