### ISSUE TITLE
Metadata for CAS04 not loading correctly in mth5

### ISSUE THREAD

**Issue by kkappler** [kujaku11/mth5#105]
This relates to aurora [issue 31](url).  Specifically, Karl's comment ln Jun 6, 2022 [https://github.com/simpeg/aurora/issues/31#issuecomment-1148155914](url)

**Comment by kkappler** [comment]
The fix Laura created is to replace:
```
returned_chan = cha_inv.networks[0].stations[0].channels[0]
returned_sta.channels.append(returned_chan)
```
with 
```
for returned_chan in cha_inv.networks[0].stations[0].channels:
    returned_sta.channels.append(returned_chan)
```

But I cannot push because of a flake8 complaint:
```
git commit -a -m"bug fix"
warning: CRLF will be replaced by LF in mth5/clients/make_mth5.py.
The file will have its original line endings in your working directory.
[WARNING] The 'rev' field of repo 'https://github.com/ambv/black' appears to be a mutable reference (moving tag / branch).  Mutable references are never updated after first install and are not supported.  See https://pre-commit.com/#using-the-latest-version-for-a-repository for more details.  Hint: `pre-commit autoupdate` often fixes this.
black....................................................................Passed
flake8...................................................................Failed
- hook id: flake8
- exit code: 1

mth5/clients/make_mth5.py:59:5: C901 'MakeMTH5.make_mth5_from_fdsnclient' is too complex (30)
```

@laura-iris when you get back on the week of 27 June, can you work with @timronan and see about factoring this method so that it passes flake8?

**Comment by kkappler** [comment]
While we are reviewing these methods, it would be nice to address:

- [ ] MakeMTH5.make_mth5_from_fdsnclient() accepted a kwarg `file_name=""`.  Normally, it uses self.make_filename() to generate the filename, and that is fine, but as a user, I would like to be able to pass a kwarg overriding this.

**Comment by kujaku11** [comment]
should be fixed now.
