### ISSUE TITLE
Adapt LEMI reader to handle runs split across multiple files

### ISSUE THREAD

**Issue by kkappler** [kujaku11/mth5#107]
In general, it is recommended to group the LEMI files in folders per station.

Within a station folder, there can be many files.

Every file is associated with exactly one run. However, some runs are associated with more than one file.

Therefore it is desirable to group the files according to their runs.

The basic functionality should be the ability to point at a folder and return a Data Frame that lists the files with a column for run_id.  The LEMI reader also needs to be modified to accept a list of filenames (associated with a run), rather than just one .TXT file.  This can be done either by
1. Reading in each file and then providing a self._merge(other) method
2. Replacing self.fn with self.fn_list

**Comment by kujaku11** [comment]
Working on it.

I think we could add a function that searches for all '.TXT' files in the given directory and then in read you could specify which file numbers you want to read, default would be all.  

Alternatively we could overwrite the `__add__` function to just append the data dataframes.

**Comment by kujaku11** [comment]
This has been fixed in with `mth5.io.lemi.LEMICollection` which concatenates `pandas.DataFrames` of each file.
