### ISSUE TITLE
Future Warning in channel_ts

### ISSUE THREAD

**Issue by kkappler** [kujaku11/mth5#113]
Minor issue, but I always get a `FutureWarning` that pd.date_range is deprecating the kwarg "closed" for "inclusive".

Closed usage:
> closed{None, ‘left’, ‘right’}, optional

    Make the interval closed with respect to the given frequency to the ‘left’, ‘right’, or both sides (None, the default).

Inclusive usage:

> inclusive{“both”, “neither”, “left”, “right”}, default “both”

    Include boundaries; Whether to set each bound as closed or open.

    New in version 1.4.0.

Previous configuration was `closed=None`, I think this corresponds to `inclusive=“both”`

I tried changing the code but found that since I am on pandas version 1.3, inclusive is not recognized as a keyword and I get 
`TypeError: _generate_range() got an unexpected keyword argument 'inclusive'`

Since in either case we are using the default configuration, I suggest we just remove this kwarg entirely instead of changing it.

**Comment by kujaku11** [comment]
I started seeing this as well.  I'll experiment with removing the keyword if the defaults work.

**Comment by kujaku11** [comment]
@kkappler I removed the key word, but there is still a future warning.  According to Pandas, this is possibly a bug and maybe updated in future releases.

**Comment by kujaku11** [comment]
Should be fixed in PR #103
