### ISSUE TITLE
add setup.py to mth5_test_data repo

### ISSUE THREAD

**Issue by kkappler** [kujaku11/mth5#15]
Once there is a setup then we can make this package (and the data) accessable by adding the following to say util.py:

________________________________________________________________
import inspect
import os
import mth5_test_data

MTH5_TEST_DATA_DIR = os.path.dirname(inspect.getfile(mth5_test_data))
#may need one more os.path.dirname() on there, and could cast to Path() as well
________________________________________________________________

**Comment by kujaku11** [comment]
Good idea.

If we want to use Path it could be something like:

MTH5_TEST_DATA_DIR = Path(inspect.getfile(mth5_test_data).parent

**Comment by kkappler** [comment]
@kujaku11 :
I created the setup.py and the functionality to do for example:
>>> from mth5_test_data.util import MTH5_TEST_DATA_DIR
>>> MTH5_TEST_DATA_DIR
PosixPath('/home/kkappler/.cache/iris_mt/mth5_test_data')

but I cannot push.  I think I do not have permission viz:

remote: Permission to kujaku11/mth5_test_data.git denied to kkappler.

**Comment by kkappler** [comment]
pushed this change.  There is now a setup.py and the test data directory is importable.
