### ISSUE TITLE
FC xarray and csv data for testing

### ISSUE THREAD

**Issue by kkappler** [kujaku11/mth5#151]
Make an example function to ingest formatted xarrays to use with developing FC array tests such as [this one](https://github.com/kujaku11/mth5/blob/fc/tests/version_1/test_fcs.py):

TLDR:
```
from aurora.test_utils.mth5.fc_helpers import read_fc_csv
xrds_obj = read_fc_csv(csv_name)
```

Detailed Notes:

Karl originally shared some csv dumps of synthetic stft (FC) arrays.
These were made by dumping the stft arrays while running:

```
tmp = TestSyntheticProcessing()
tmp.setUp()
tmp.test_can_output_tf_class_and_write_tf_xml()
```

While we are developing the FC branches I made a minor modification to aurora:
I added a kwarg `save_fcs=False` to `process_mth5`.  If this is True, the fcs get dumped to csv via:

```
if save_fcs:
    csv_name = f"{row.station_id}_dec_level_{i_dec_level}.csv"
    stft_df = stft_obj.to_dataframe()
    stft_df.to_csv(csv_name)
```

I also set `save_fcs=True` in `tests/synthetic/test_processing.py` in the function `process_synthetic_2()`
So calling test_processing.py will result in csvs on your system, 
or you can
```
tmp = TestSyntheticProcessing()
tmp.setUp()
tmp.test_can_process_other_station()
```

Results is that in the synthetic directory will be:

> test2_dec_level_0.csv
test2_dec_level_1.csv
test2_dec_level_2.csv
test2_dec_level_3.csv

with md5sums:

> a3f2234c1e62fdc1962c8247eb5c09cf  test2_dec_level_0.csv
03dc941fc9fbff9247bd23defc4bbd3e  test2_dec_level_1.csv
cf69e05bc93ea67d869a9e561cdd820b  test2_dec_level_2.csv
[test2_dec_level_3.csv](https://github.com/kujaku11/mth5/files/11713301/test2_dec_level_3.csv)
[test2_dec_level_2.csv](https://github.com/kujaku11/mth5/files/11713302/test2_dec_level_2.csv)
0675cf052086f8f4a02d44075c91cd80  test2_dec_level_3.csv

If you want to read those back into the stft_obj data structure you can import `read_fc_csv` from 
`aurora/aurora/test_utils/mth5/fc_helpers.py`

usage:
`df =read_fc_csv(csv_name, as_xarray=False)`
I confirm that `(df==stft_df).all().all()` is `True`

or 
`xrds_obj =read_fc_csv(csv_name, as_xarray=True)`
I also confirm `(xrds_obj==stft_obj).all().all()` is `True`
 
These tools should allow some sample xarray fc objects to be available for testing.

@kujaku11 give it a try and lmk if any issues.

csvs also attached here for the record
[test2_dec_level_1.csv](https://github.com/kujaku11/mth5/files/11713303/test2_dec_level_1.csv)
[test2_dec_level_0.csv](https://github.com/kujaku11/mth5/files/11713304/test2_dec_level_0.csv)
[test2_dec_level_2.csv](https://github.com/kujaku11/mth5/files/11713306/test2_dec_level_2.csv)
[test2_dec_level_3.csv](https://github.com/kujaku11/mth5/files/11713307/test2_dec_level_3.csv)

**Comment by kujaku11** [comment]
@kkappler Just to be clear about the various sample rates to keep track of if we are only going to store the spectrogram without the coordinates of time and frequency.

- `sample_rate_window_step` [units = seconds]: the time difference between windows ($\Delta_t$)
- `sampe_rate_decimation_level` [unit=samples per second]: sample rate in time of the decimation level
- `sample_rate_frequency` [units = samples per second]: frequency sample rate from dc to nyquist (`sample_rate_decimation_level` / 2) based on the size of the window ($\Delta_f$)

![fc_spectrogram](https://github.com/kujaku11/mth5/assets/2100870/be1f5ddd-51d7-41c8-a479-4499c121968b)

Then we can reconstruct the time and frequency arrays
```
end_time = start_time + (n_time_samples - 1) / sampe_rate_window_ste
time = pd.date_range(
                     start=start_time, 
                     end=end_time, 
                     periods=n_time_samples)

frequency = np.linspace(0, sample_rate_decimation_level/2, window_size)
```

**Comment by kujaku11** [comment]
This is sorted with PR #143
