### ISSUE TITLE
Unexpected group.size dtype (<i4, not <i8)

### ISSUE THREAD

**Issue by kkappler** [kujaku11/mth5#186]
Have an mth5, and am able to open it, interact and process it, exporting xml and edi files.

However, on exit from the processing, encounter a the following error:

>24:01:15T16:39:44 | ERROR | line:230 |mth5.tables.mth5_table | add_row | Data types are not equal. Input dtypes: [('survey', 'S30'), ('station', 'S30'), ('run', 'S20'), ('latitude', '<f8'), ('longitude', '<f8'), ('elevation', '<f8'), ('component', 'S20'), ('start', 'S36'), ('end', 'S36'), ('n_samples', '<i8'), ('sample_rate', '<f8'), ('measurement_type', 'S30'), ('azimuth', '<f8'), ('tilt', '<f8'), ('units', 'S60'), ('hdf5_reference', 'O'), ('run_hdf5_reference', 'O'), ('station_hdf5_reference', 'O')] Table dtypes: [('survey', 'S30'), ('station', 'S30'), ('run', 'S20'), ('latitude', '<f8'), ('longitude', '<f8'), ('elevation', '<f8'), ('component', 'S20'), ('start', 'S36'), ('end', 'S36'), ('n_samples', '<i4'), ('sample_rate', '<f8'), ('measurement_type', 'S30'), ('azimuth', '<f8'), ('tilt', '<f8'), ('units', 'S60'), ('hdf5_reference', 'O'), ('run_hdf5_reference', 'O'), ('station_hdf5_reference', 'O')]

The error is happening when the channel summary is being generated on closing the file.

Distilling the error to the diffference it is this:
INPUT: ('n_samples', '<i8'),
TABLE: ('n_samples', '<i4'),

The dtype of n_samples in my channel summary is int32, but it is expected to be int64.

I looked at the parent mth5 and that is the case:
```
mth5_obj.channel_summary.to_dataframe()["n_samples"]
0    6389760
1    6389760
2    6389760
3    6389760
4    6389760
5    6389760
6    6389760
7    6389760
8    6389760
9    6389760
Name: n_samples, dtype: int32
```

but looking at any of my usual mth5 examples, i see:
mm.channel_summary.to_dataframe()["n_samples"]
0    40000
1    40000
2    40000
3    40000
4    40000
Name: n_samples, dtype: int64

I am 99% sure that this is due to [this commit](https://github.com/kujaku11/mth5/commit/b1e5acc2241330e712b7692bb523f6737b06363c)

Where i had an int32 as num_channels" which was making the make_mth5 fail, so I added int32 to the list of values that just returns itself in `mth5.helpers.from_numpy_type`

probably, what I should have done is if the value was of type np.int32, return int(value).

**Comment by kkappler** [comment]
@kujaku11 to avoid this sort of thing in future, we could force dtyping on tables in general

**Comment by kkappler** [comment]
This appears to actually be an OS dependent issue :/

```
m.open_mth5("junk.h5", mode="a")
df = m.channel_summary.to_dataframe()
df.n_samples
```

**Linux:**

0    0
Name: n_samples, dtype: int64


**Windows**
0    0
Name: n_samples, dtype: int32

**Comment by kkappler** [comment]
@kujaku11 can you think of a patch that would force the column to have an OS-independent dtype?

**Comment by kujaku11** [comment]
@kkappler interesting, always thought Python was platform independent.  I guess the only way would be to force type to be int64 or what you want. Because we are making the dataframe on the fly this shouldn't be too much of an issue.  You could also do an `astype` on the dataframe column as an intermediate step.

**Comment by kkappler** [comment]
@kujaku11 I think it might be trickier than that ... in `ChannelSummaryTable` `self._dtype = CHANNEL_DTYPE` in the `__init__` method.

The issue is with CHANNEL_DTYPE in mth5.mth5.__init__.py

which uses np.dtype while defining the columns of the dtype.  That CHANNEL_DTYPE is routinely checked against when rows are added or the h5 is modified.

The essence of the issue is 
`np.dtype("n_samples", int)`
returns:
dtype('int64') on linux
dtype('int32') on Windows

The issue is discussed [here](https://stackoverflow.com/questions/36278590/numpy-array-dtype-is-coming-as-int32-by-default-in-a-windows-10-64-bit-machine)

I think my exception yesterday was from building a file on windows and adding FC layers on linux.

Maybe I can add a try/except to the mth5_table check_dtypes method, that changes `other_dtype` to match the expected value.

**Comment by kkappler** [comment]
@kujaku11: I added a workaround that is not terrible.  Let's review the changes on `patches` branch at the end of the week if possible.

**Comment by kkappler** [comment]
Some more context, alternative workarounds, and a comment on testing:

Recently I added what was effectively allowing np.int32 to pass through `from_numpy_dtype`.  I believe this was needed when I was building mth5 on windows from metronix files.  Probably, it would have been better to cast the metronix metadata channel number to int64 rather than modify mth5.

However, that is besides the issue of non-cross-platform h5 files -- which I believe we were unaware of until recently.  The trouble seems to be that while channel_summary .summarize does start off by clearing the table, the mth5 remembers the dtype of the table.  So maybe if we redefine the dtype (via the system executing the summary) we could get around this.

We might want to consider adding the following block to `from_numpy_dtype` within mth5/helpers.py
```
    if isinstance(
        value,
        (
            np.int32,
        )
    ):
        return np.int64(value)
```

This should force windows to use int64 in the table, making it the same on all platforms ... but, would an unintended consequence be that we lose int32 storage of raw data in counts?? 

**And, could this be related to the 3x file size bug?**  

Maybe expanding the github actions tests to run on windows as well, and even better (I don't know how to though) have a test environment where we could make a synthetic mth5 on windows, and then operate on the file with linux and vice versa.

**Comment by kkappler** [comment]
- mth5.__init__ CHANNEL_DTYPE_LIST could have ("n_samples", int), element replaced with ("n_samples", np.int64),
- This will force the table to always be int64 for all future tables.

- To guard against old files having issues, we can on opening the file, check that the expected dtypes are present, and if not, call channel_summary.summarize() to regenerate the table.

- This means that channel_summary.summarize() must get its dtype from the code, and not from the old version of the table as is done around line 340 of mth5_table.  Rather it can take it from self.dtype for which channel_summary.dtype is mth5.__init__ CHANNEL_DTYPE
