### ISSUE TITLE
Setup GitActions

### ISSUE THREAD

**Issue by kujaku11** [kujaku11/mth5#19]
Setup GitActions so that the workflow is comprehensive.  
@lheagy  Any chance you could take a look at this, or walk me through the process.  Seems like there is a bunch of stuff to use.

**Comment by lheagy** [comment]
For sure, I am happy to take a look!

**Comment by kujaku11** [comment]
- Testing branch worked,
- Accepted pull request to merge with master, workflow worked
- Merged master with develop, workflow did not pass because it is using h5py version 2.10 and that apparently fails, where as Master installs h5py 3.1 and works.
- I don't see any difference in the files between the 2 branches. @lheagy Any thoughts on what's going on?

**Comment by lheagy** [comment]
hmm, I am not too sure, but on first glance, I wonder if it is something to do with dependencies? I am wondering here which version of numpy is installed and if that makes any difference? 

https://github.com/kujaku11/mth5/blob/db627866788697a37aa344e8b7d4129e3ea864e3/pyproject.toml#L28

**Comment by kujaku11** [comment]
Good spot that's probably the issue.

**Comment by kujaku11** [comment]
Install of mt_metadata now runs, but its missing .json and logging_config.yaml files.  Added them in the mt_metadata/MANIFEST.in file and in the mt_metadata/setup.py.  But for that hasn't worked yet. Still testing.  Anyone want to test that they can successfully run:
`pip install git+https://github.com/kujaku11/mt_metadata.git`

**Comment by kujaku11** [comment]
Fixed the issues with bundling .json files with mt_metadata.  Now the issue is installing mth5_test_data. @lheagy @kkappler @domfournier  do you guys have any thoughts on the best way to install/download data from the mth5_test_data repository?  Do we just make a setup.py and MANIFEST.in to install all the data?
