### ISSUE TITLE
Station summary fails if date time has no milliseconds

### ISSUE THREAD

**Issue by kujaku11** [kujaku11/mth5#214]
This was an issue that was addressed for the `channel_summary` but was not addressed for the `station_summary`.  This has to do with pandas datetime, if a previous input has milliseconds then it expects milliseconds and if there are none it fails, need to add a key word `mixed` as we have in the `channel_summary`.

**Comment by kkappler** [comment]
I recall that when the mixed fix was originally implemented for channel summary it solved a specific problem case, _but_ other cases broke and the patch needed an additional update.  The solution on channel summary was to use a try/except strategy where the mixed keyword was one option and the previous syntax was the other.
