### ISSUE TITLE
Compute Sample Rate - Expensive Median Computation

### ISSUE THREAD

**Issue by dequiroga** [kujaku11/mth5#241]
The use of ChannelTS.compute_sample_rate is significantly slow. (Significant when used repeatedly in large datasets)

Once in a while, if the sample rate is not defined, MTH5 computes it from the time array, and it uses the median of the time differences.  When using this functionality repeatedly (for large datasets) this results in a significant time inefficiency. 

I have been having the same results (but substantially faster) using the mode. e.g.:  

### Take the mode?
> best_dt, counts = scipy.stats.mode(dt_array)

Another idea would be doing some sort of weighted average, but this does not seem to be as robust... e.g.: 

### Weighted average of the unique dt occurrences (weighted by counts)?
> n_samples = len(dt_array)
> uniques, counts = np.unique(dt_array, return_counts=True) 
> weights = counts / n_samples
> best_dt = np.sum(uniques * weights)

**Comment by kujaku11** [comment]
@dequiroga This is great, we've been dealing with this problem for a while now, but hadn't used much big data.  I like your method of using scipy.stats, that probably is much faster than np.median.  

Could you draft a pull request?

**Comment by kkappler** [comment]
@kujaku11 can you please add permission for @dequiroga to PR into mth5?

**Comment by dequiroga** [comment]
Thanks @kujaku11, see the draft PR #246
