### ISSUE TITLE
Build Data Frame that Indexes Acquisition Runs

### ISSUE THREAD

**Issue by timronan** [kujaku11/mth5#47]
There should be a function that outputs a pandas data frame containing the acquisition runs available in an MTH5  expirment. Each row should represent one run and should contain: Station ID, Run ID, List of Channels, Sample Rate, Starttime, Endtime. 

This function will verify that all channels listed per run will have the same sample rate. If there is an inter-run sample rate inconsistency than an error will be thrown. 

There should be an optional argument that will make the output of the function a data frame with one channel per each row. So the DF columns would be: Station ID, Run ID, Channel, Sample Rate, Starttime, Endtime.

**Comment by kujaku11** [comment]
This has been added in `channel_summary`.
