### ISSUE TITLE
Unexpected value for channels_recorded_electric, channels_recorded_magnetic

### ISSUE THREAD

**Issue by kkappler** [kujaku11/mth5#49]
Here is a screenshot of an mth5 dataset as it prints to screen

I have only 4 channels, ex, ey, hx, hy

Its puzzling that the channels_recorded_electric seems to have so many entries ... I would have expected ["ex", "ey"]

![channels_recorded_seems_long](https://user-images.githubusercontent.com/1154939/132758482-3d24ee6f-bcec-4686-acc7-0c8c525de54d.png)

**Comment by kujaku11** [comment]
This has been fixed.
