### ISSUE TITLE
make_mth5 example not packing time series into container

### ISSUE THREAD

**Issue by kkappler** [kujaku11/mth5#65]
I tried running  examples/notebooks/make_mth5_driver.ipynb and I do get an h5 file, but it is only 222k which seems small. 

After the notebook, I added the following commands in the cells:
```
cas04 = mth5_obj.stations_group.get_station("CAS04")
run_b = cas04.get_run('b')
ts = run_b.to_runts()
ts.dataset.max()
ts.dataset.min()
```

I wind up with max and min being zero everywhere.  Not sure what is going on but we should have some data in this file.
![Screenshot from 2021-10-23 14-02-39](https://user-images.githubusercontent.com/1154939/138571535-1e078058-3263-430c-a9a9-ac5853db31dc.png)

**Comment by kujaku11** [comment]
Should be fixed with PR #154
