### ISSUE TITLE
Fail to propagate time-period into channel summary

### ISSUE THREAD

**Issue by kujaku11** [kujaku11/mth5#7]
When reading in metadata to create a channel the stations_group.summary_table does not populate with the appropriate date and time for time_period.start time_period.end

This occurs with mth5/examples/make_mth5_file_from_xml.py

Namely this issue will occur anytime metadata is updated after a channel is added to a run group.  There needs to be functionality to update the stations_group.summary_table entry when metadata is updated.   This should be done automatically and not be left to the user for consistency.  Moreover, there should be a test when a file is closed to make sure that all the channel entries are consistent.

**Comment by kkappler** [comment]
This is solved, most likely
