### ISSUE TITLE
Restructure Clients and Add ScienceBase to the Clients

### ISSUE THREAD

**Issue by kujaku11** [kujaku11/mth5#81]
We have FDSN clients working for the most part, now we should look at adding other clients.  One in particular that has MHT5 files already is USGS ScienceBase.  We can use `sciencebasepy` as the tool to get data and data availability.  This is not a data services like IRIS, its an file drive.  So you can only pull the files it has on it and not parts of files like you can with IRIS, namely you can't request a time period.  

If we do this we should restructure `clients` to be more plugin friendly.  For instance have a `FDSN` module and a `ScienceBase` module that `make_mth5` can load.  This will make it easier to extent to other clients

|-> clients
   
    |-> make_mth5
    |-> fdsn
    |-> science_base
    |-> others

 @kkappler and @timronan  what do you guys think?  This would sort of go along with Karl's intuition to split up some of the functions in make_mth5.  I'll create a branch `clients` that we can work on.

**Comment by timronan** [comment]
@kujaku11 this sounds good. Would the structure be similar to:
```
|-> clients
|--> make_mth5
|----> fdsn
|----> science_base
|----> others
```
So a switch could be added into  make_mth5 which would direct which client is called. It seems like this would allow us to reuse a lot of the logic in Make_MTH5 and make client specific plugins as you mention above.

**Comment by kujaku11** [comment]
Done with PR #139
