### ISSUE TITLE
CAS04 data Not Found at IRIS

### ISSUE THREAD

**Issue by kujaku11** [kujaku11/mth5#91]
@timronan   The `test_make_mth5` fails because no data is found for ZU/CAS04.  I'm guessing that you are starting to move stations around, is CAS04 one of them, is this the case?  Can you point towards the new network location?

I added a try/except statement in the test and an error is raise if the except is triggered stating no data found at IRIS, just for book keeping and clarity with the tests.

**Comment by timronan** [comment]
@kujaku11 I was on PTO last week and the archive was being updated. I will resolve this issue tomorrow. Sorry for the confusion.

**Comment by timronan** [comment]
@kujaku11 all of the data has been rearchived. This test case should pass again.

**Comment by timronan** [comment]
@kujaku11 ZU CAS04 was moved to 8P CAS04. The network in the test case need to be updated. Here is the IRIS availability. 

https://service.iris.edu/fdsnws/availability/1/query?format=text&net=8P&sta=CAS04&starttime=2020-06-12T18:32:17&endtime=2020-07-13T19:00:00&orderby=nslc_time_quality_samplerate&includerestricted=false&nodata=404

**Comment by kujaku11** [comment]
@timronan Thanks. I adapted all test and data request to use `8p`.
