### ISSUE TITLE
How to create Mth5 file from lots of .z3d channel files?

### ISSUE THREAD

**Issue by k-a-mendoza** [kujaku11/mth5#95]
Hey all,
I know this project is still in its infancy, but I'm trying to familiarize myself with it as I truly believe this is the way to go.

I'm doing a survey using Zen's where 2 permanent stations are deployed for the duration of the survey (mostly), and 4 telluric stations only rove around a number of sites. Some of the tellurics are reoccupied intermittently. So I now have a substantial database of .z3d files.

Following the tutorials on the readthedocs.io page, I did the following to read them in:

```python
zonge_files = glob.glob('MT_data/snapshot 1/**/*.z3d', recursive=True)
mt_channels = []
for x in zonge_files:
    try:
        mt_channel = mth5.read_file(x)
        mt_channels.append(mt_channel)
    except:
        print('there were problems')
```
It works for most of the files, but now I have a huge list of what are channel timeseries. Exploring the properties a bit, it appears each TS has metadata corresponding to the station and time it belonged to, as well as other channel data. 

My question is, how do I collate all these channels into a single survey object? Do I have to manually parse each channel's metadata and add them to a master Mth5 experiment? For reference, there's about ~2-300 individual .z3d channel files

**Comment by kujaku11** [comment]
@k-a-mendoza good question.  I would try something like this.  You can read each z3d file which has station information in it.  Once you read that file you can add a station, if the station already exists it will return that station group.  Then you can add a run, again if the run already exists you will get back the existing run, finally you can add the channel:

```
# open mth5 file
m = mth5.MTH5(h5_fn)
m.open_mth5()

# add survey
new_survey = m.add_survey("example")
# update any survey metadata that you have
new_survey.metadata.acquired_by.author = "K. Mendoza"
new_survey.write_metadata()

# add station metadata from z3d files
for fn in z3d_file_list:
    mtts_obj = read_file(zen_dir.joinpath(fn.filename))

    station_group = new_survey.add_station(
        mtts_obj.station_metadata.id, station_metadata=mtts_obj.station_metadata,
    )

    run_id = station_group.locate_run(mtts_obj.sample_rate, mtts_obj.start)
    if run_id is None:
        run_id = station_group.make_run_name()
        mtts_obj.run_metadata.id = run_id

    run_group = station_group.add_run(run_id, mtts_obj.run_metadata)

    # need to update metadata
    station_group.validate_station_metadata()

if not interact:
    m.close_mth5()
```

For a more elegant solution have a look at [Z3DCollection](https://github.com/kujaku11/mt_sb_archiving/blob/main/archive/utils/z3d_collection.py) and [Example of archiving Z3D files USGS style](https://github.com/kujaku11/mt_sb_archiving/blob/main/archive/archive.py).  These are what I use to archive USGS data on Science Base.  So there is some superfluous code that doesn't pertain to you use case but there is a work flow that could be useful.

**Comment by k-a-mendoza** [comment]
@kujaku11 

This is great. Thanks!
This is my modified solution, though there is an issue with adding runs.

while I verified .z3d files belonging to different runs but the same station have different start times, it appears that
the ```locate_run()``` method returns the default '001' run regardless. So by running the below it appears that previous runs are being overwritten. 

```python
from mth5.mth5 import MTH5
import glob
# glob .z3d files
zen_channels= glob.glob(f'{experiment_directory}{os.sep}**{os.sep}*.z3d',recursive=True)

fn='example_name.h5'
m = MTH5(fn)
m.open_mth5()

# add survey
new_survey = m.add_survey("example")
# update any survey metadata that you have
new_survey.metadata.acquired_by.author = "K. A. Mendoza"
new_survey.write_metadata()

# add station metadata from z3d files
for zen_file in valid_zen_channels:
    print(zen_file)
    mtts_obj = mth5.read_file(zen_file)

    # The way these .z3d files were created required a numeric station name.
    # Here I format the station name with an appropriate string combo relevant to the project, then reassign 
    # to the station_metadata.id
    station = f'ftm{str(mtts_obj.station_metadata.id).zfill(4)}'
    mtts_obj.station_metadata.id=station

    station_group = new_survey.stations_group.add_station(
        station, station_metadata=mtts_obj.station_metadata,
    )

    run_id = station_group.locate_run(mtts_obj.sample_rate, mtts_obj.start)
]    if run_id is None:
        run_id = station_group.make_run_name()
        mtts_obj.run_metadata.id = run_id
    run_group = station_group.add_run(run_id, mtts_obj.run_metadata)

    # need to update metadata
    station_group.validate_station_metadata()

m.close_mth5()
```

**Comment by k-a-mendoza** [comment]
I get correct behavior from ``` .locate_run()``` by changing the dataframe slicing operation from:

```python
 station_group.run_summary[(station_group.run_summary.sample_rate==mtts_obj.sample_rate) & \
                                                  (station_group.run_summary.start==mtts_obj.start)]
```

to 

```python
 station_group.run_summary[(station_group.run_summary.sample_rate==mtts_obj.sample_rate) & \
                                                  (station_group.run_summary.start==np.datetime64(mtts_obj.start.iso_str))]
```

this would indicate that the ```__eq__``` method for ```MTime``` object is incorrect/bugged.

**Comment by kujaku11** [comment]
@k-a-mendoza added a Z3DCollection in PR #103 should be easier to collect a bunch of z3d files now. Closing for now.
